services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  app:
    image: ghcr.io/nakchoi/wanted-pre-onboarding-backend:deploy
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8080:8080"
    restart: always
