services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE : test
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  app:
    image: ghcr.io/nakchoi/wanted-pre-onboarding-backend:deploy
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    links:
      - db:db
    ports:
      - "8080:8080"
    restart: always
