spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  datasource:
#    url: jdbc:mysql://localhost:3306/mysqldb
    url: jdbc:mysql://db/test
    username: root
    password: "test1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 300

